<?php
session_start();
?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form method="post">
      <input type="text" name="nick" placeholder="Coloque seu nome de perfil no lol"><br>
      Voce procura parceiros para:
      <select name="objetivo">
        <option value="lazer">Lazer</option>
        <option value="ranqueada">Ranqueada</option>
        <option value="campeonato">Campeonato</option>
      </select><br>
      De que estado voce é:
      <select name="estado">
        <option value="AC">AC</option>
  			<option value="AL">AL</option>
  			<option value="AP">AP</option>
  			<option value="AM">AM</option>
  			<option value="BA">BA</option>
  			<option value="CE">CE</option>
  			<option value="DF">DF</option>
  			<option value="ES">ES</option>
  			<option value="GO">GO</option>
  			<option value="MA">MA</option>
  			<option value="MT">MT</option>
  			<option value="MS">MS</option>
  			<option value="MG">MG</option>
  			<option value="PA">PA</option>
  			<option value="PB">PB</option>
  			<option value="PR">PR</option>
  			<option value="PE">PE</option>
  			<option value="PI">PI</option>
  			<option value="RJ">RJ</option>
  			<option value="RN">RN</option>
  			<option value="RS">RS</option>
  			<option value="RO">RO</option>
  			<option value="RR">RR</option>
  			<option value="SC">SC</option>
  			<option value="SP">SP</option>
  			<option value="SE">SE</option>
  			<option value="TO">TO</option>
      </select><br>
      Selecione seus melhores campeões:<br>
      <select name="camp1">
        <option value="null">nenhum</option>
        <option value="1">Aatrox</option>
        <option value="2">Ahri</option>
        <option value="3">Akali</option>
        <option value="4">Alistar</option>
        <option value="5">Amumu</option>
        <option value="6">Anivia</option>
        <option value="7">Annie</option>
        <option value="8">Ashe</option>
        <option values="9">Aurelion</option>
        <option values="10">Azir</option>
        <option values="11">Bardo</option>
        <option values="12">Blitzcrank</option>
        <option values="13">Brand</option>
        <option values="14">Braum</option>
        <option values="15">Caitlyn</option>
        <option values="16">Camille</option>
        <option values="17">Cassiopeia</option>
        <option values="18">Cho'Gath</option>
        <option values="19">Corki</option>
        <option values="20">Darius</option>
        <option values="21">Diana</option>
        <option values="22">Dr. Mundo</option>
        <option values="23">Draven</option>
        <option values="24">Ekko</option>
        <option values="25">Elise</option>
        <option values="26">Evelynn</option>
        <option values="27">Ezreal</option>
        <option values="28">Fiddlesticks</option>
        <option values="29">Fiora</option>
        <option values="30">Fizz</option>
        <option values="31">Galio</option>
        <option values="32">Gangplank</option>
        <option values="33">Garen</option>
        <option values="34">Gnar</option>
        <option values="35">Gragas</option>
        <option values="36">Graves</option>
        <option values="37">Hecarim</option>
        <option values="38">Heimerdinger</option>
        <option values="39">Illaoi</option>
        <option values="40">Irelia</option>
        <option values="41">Ivern</option>
        <option values="42">Janna</option>
        <option values="43">Jarvan IV</option>
        <option values="44">Jax</option>
        <option values="45">Jayce</option>
        <option values="46">Jhin</option>
        <option values="47">Jinx</option>
        <option values="48">Kai'Sa</option>
        <option values="49">Kalista</option>
        <option values="50">Karma</option>
        <option values="51">Karthus</option>
        <option values="52">Kassadin</option>
        <option values="53">Katarina</option>
        <option values="54">Kayle</option>
        <option values="55">Kayn</option>
        <option values="56">Kennen</option>
        <option values="57">Kha'Zix</option>
        <option values="58">Kindred</option>
        <option values="59">Kled</option>
        <option values="60">Kog'Maw</option>
        <option values="61">LeBlanc</option>
        <option values="62">Lee Sin</option>
        <option values="63">Leona</option>
        <option values="64">Lissandra</option>
        <option values="65">Lucian</option>
        <option values="66">Lulu</option>
        <option values="67">Lux</option>
        <option values="68">Malphite</option>
        <option values="69">Malzahar</option>
        <option values="70">Maokai</option>
        <option values="71">Master Yi</option>
        <option values="72">Miss Fortune</option>
        <option values="73">Mordekaiser</option>
        <option values="74">Morgana</option>
        <option values="75">Nami</option>
        <option values="76">Nasus</option>
        <option values="77">Nautilus</option>
        <option values="78">Nidalee</option>
        <option values="79">Nocturne</option>
        <option values="80">Nunu e Willump</option>
        <option values="81">Olaf</option>
        <option values="82">Orianna</option>
        <option values="83">Ornn</option>
        <option values="84">Pantheon</option>
        <option values="85">Poppy</option>
        <option values="86">Pyke</option>
        <option values="87">Quinn</option>
        <option values="88">Rakan</option>
        <option values="89">Rammus</option>
        <option values="90">Rek'sai</option>
        <option values="91">Renekton</option>
        <option values="92">Rengar</option>
        <option values="93">Riven</option>
        <option values="94">Rumble</option>
        <option values="95">Ryze</option>
        <option values="96">Sejuani</option>
        <option values="97">Shaco</option>
        <option values="98">Shen</option>
        <option values="99">Shyvana</option>
        <option values="100">Singed</option>
        <option values="101">Sion</option>
        <option values="102">Sivir</option>
        <option values="103">Skarner</option>
        <option values="104">Sona</option>
        <option values="105">Soraka</option>
        <option values="106">Swain</option>
        <option values="107">Syndra</option>
        <option values="108">Tahm Kench</option>
        <option values="109">Taliyah</option>
        <option values="110">Talon</option>
        <option values="111">Taric</option>
        <option values="112">Teemo</option>
        <option values="113">Thresh</option>
        <option values="114">Tristana</option>
        <option values="115">Trundle</option>
        <option values="116">Tryndamere</option>
        <option values="117">Twisted Fate</option>
        <option values="118">Twitch</option>
        <option values="119">Udyr</option>
        <option values="120">Urgot</option>
        <option values="121">Varus</option>
        <option values="122">Vayne</option>
        <option values="123">Veigar</option>
        <option values="124">Vel'Koz</option>
        <option values="125">Vi</option>
        <option values="126">Viktor</option>
        <option values="127">Vladimir</option>
        <option values="128">Volibear</option>
        <option values="129">Warwick</option>
        <option values="130">Wukong</option>
        <option values="131">Xayah</option>
        <option values="132">Xerath</option>
        <option values="133">Xin Zhao</option>
        <option values="134">Yasuo</option>
        <option values="135">Yorick</option>
        <option values="136">Zac</option>
        <option values="137">Zed</option>
        <option values="138">Ziggs</option>
        <option values="139">Zilean</option>
        <option values="140">Zoe</option>
        <option values="141">Zyra</option>
      </select>
      <select name="camp2">
        <option value="null">nenhum</option>
        <option value="1">Aatrox</option>
        <option value="2">Ahri</option>
        <option value="3">Akali</option>
        <option value="4">Alistar</option>
        <option value="5">Amumu</option>
        <option value="6">Anivia</option>
        <option value="7">Annie</option>
        <option value="8">Ashe</option>
        <option values="9">Aurelion</option>
        <option values="10">Azir</option>
        <option values="11">Bardo</option>
        <option values="12">Blitzcrank</option>
        <option values="13">Brand</option>
        <option values="14">Braum</option>
        <option values="15">Caitlyn</option>
        <option values="16">Camille</option>
        <option values="17">Cassiopeia</option>
        <option values="18">Cho'Gath</option>
        <option values="19">Corki</option>
        <option values="20">Darius</option>
        <option values="21">Diana</option>
        <option values="22">Dr. Mundo</option>
        <option values="23">Draven</option>
        <option values="24">Ekko</option>
        <option values="25">Elise</option>
        <option values="26">Evelynn</option>
        <option values="27">Ezreal</option>
        <option values="28">Fiddlesticks</option>
        <option values="29">Fiora</option>
        <option values="30">Fizz</option>
        <option values="31">Galio</option>
        <option values="32">Gangplank</option>
        <option values="33">Garen</option>
        <option values="34">Gnar</option>
        <option values="35">Gragas</option>
        <option values="36">Graves</option>
        <option values="37">Hecarim</option>
        <option values="38">Heimerdinger</option>
        <option values="39">Illaoi</option>
        <option values="40">Irelia</option>
        <option values="41">Ivern</option>
        <option values="42">Janna</option>
        <option values="43">Jarvan IV</option>
        <option values="44">Jax</option>
        <option values="45">Jayce</option>
        <option values="46">Jhin</option>
        <option values="47">Jinx</option>
        <option values="48">Kai'Sa</option>
        <option values="49">Kalista</option>
        <option values="50">Karma</option>
        <option values="51">Karthus</option>
        <option values="52">Kassadin</option>
        <option values="53">Katarina</option>
        <option values="54">Kayle</option>
        <option values="55">Kayn</option>
        <option values="56">Kennen</option>
        <option values="57">Kha'Zix</option>
        <option values="58">Kindred</option>
        <option values="59">Kled</option>
        <option values="60">Kog'Maw</option>
        <option values="61">LeBlanc</option>
        <option values="62">Lee Sin</option>
        <option values="63">Leona</option>
        <option values="64">Lissandra</option>
        <option values="65">Lucian</option>
        <option values="66">Lulu</option>
        <option values="67">Lux</option>
        <option values="68">Malphite</option>
        <option values="69">Malzahar</option>
        <option values="70">Maokai</option>
        <option values="71">Master Yi</option>
        <option values="72">Miss Fortune</option>
        <option values="73">Mordekaiser</option>
        <option values="74">Morgana</option>
        <option values="75">Nami</option>
        <option values="76">Nasus</option>
        <option values="77">Nautilus</option>
        <option values="78">Nidalee</option>
        <option values="79">Nocturne</option>
        <option values="80">Nunu e Willump</option>
        <option values="81">Olaf</option>
        <option values="82">Orianna</option>
        <option values="83">Ornn</option>
        <option values="84">Pantheon</option>
        <option values="85">Poppy</option>
        <option values="86">Pyke</option>
        <option values="87">Quinn</option>
        <option values="88">Rakan</option>
        <option values="89">Rammus</option>
        <option values="90">Rek'sai</option>
        <option values="91">Renekton</option>
        <option values="92">Rengar</option>
        <option values="93">Riven</option>
        <option values="94">Rumble</option>
        <option values="95">Ryze</option>
        <option values="96">Sejuani</option>
        <option values="97">Shaco</option>
        <option values="98">Shen</option>
        <option values="99">Shyvana</option>
        <option values="100">Singed</option>
        <option values="101">Sion</option>
        <option values="102">Sivir</option>
        <option values="103">Skarner</option>
        <option values="104">Sona</option>
        <option values="105">Soraka</option>
        <option values="106">Swain</option>
        <option values="107">Syndra</option>
        <option values="108">Tahm Kench</option>
        <option values="109">Taliyah</option>
        <option values="110">Talon</option>
        <option values="111">Taric</option>
        <option values="112">Teemo</option>
        <option values="113">Thresh</option>
        <option values="114">Tristana</option>
        <option values="115">Trundle</option>
        <option values="116">Tryndamere</option>
        <option values="117">Twisted Fate</option>
        <option values="118">Twitch</option>
        <option values="119">Udyr</option>
        <option values="120">Urgot</option>
        <option values="121">Varus</option>
        <option values="122">Vayne</option>
        <option values="123">Veigar</option>
        <option values="124">Vel'Koz</option>
        <option values="125">Vi</option>
        <option values="126">Viktor</option>
        <option values="127">Vladimir</option>
        <option values="128">Volibear</option>
        <option values="129">Warwick</option>
        <option values="130">Wukong</option>
        <option values="131">Xayah</option>
        <option values="132">Xerath</option>
        <option values="133">Xin Zhao</option>
        <option values="134">Yasuo</option>
        <option values="135">Yorick</option>
        <option values="136">Zac</option>
        <option values="137">Zed</option>
        <option values="138">Ziggs</option>
        <option values="139">Zilean</option>
        <option values="140">Zoe</option>
        <option values="141">Zyra</option>
      </select>
      <select name="camp3">
        <option value="null">nenhum</option>
        <option value="1">Aatrox</option>
        <option value="2">Ahri</option>
        <option value="3">Akali</option>
        <option value="4">Alistar</option>
        <option value="5">Amumu</option>
        <option value="6">Anivia</option>
        <option value="7">Annie</option>
        <option value="8">Ashe</option>
        <option values="9">Aurelion</option>
        <option values="10">Azir</option>
        <option values="11">Bardo</option>
        <option values="12">Blitzcrank</option>
        <option values="13">Brand</option>
        <option values="14">Braum</option>
        <option values="15">Caitlyn</option>
        <option values="16">Camille</option>
        <option values="17">Cassiopeia</option>
        <option values="18">Cho'Gath</option>
        <option values="19">Corki</option>
        <option values="20">Darius</option>
        <option values="21">Diana</option>
        <option values="22">Dr. Mundo</option>
        <option values="23">Draven</option>
        <option values="24">Ekko</option>
        <option values="25">Elise</option>
        <option values="26">Evelynn</option>
        <option values="27">Ezreal</option>
        <option values="28">Fiddlesticks</option>
        <option values="29">Fiora</option>
        <option values="30">Fizz</option>
        <option values="31">Galio</option>
        <option values="32">Gangplank</option>
        <option values="33">Garen</option>
        <option values="34">Gnar</option>
        <option values="35">Gragas</option>
        <option values="36">Graves</option>
        <option values="37">Hecarim</option>
        <option values="38">Heimerdinger</option>
        <option values="39">Illaoi</option>
        <option values="40">Irelia</option>
        <option values="41">Ivern</option>
        <option values="42">Janna</option>
        <option values="43">Jarvan IV</option>
        <option values="44">Jax</option>
        <option values="45">Jayce</option>
        <option values="46">Jhin</option>
        <option values="47">Jinx</option>
        <option values="48">Kai'Sa</option>
        <option values="49">Kalista</option>
        <option values="50">Karma</option>
        <option values="51">Karthus</option>
        <option values="52">Kassadin</option>
        <option values="53">Katarina</option>
        <option values="54">Kayle</option>
        <option values="55">Kayn</option>
        <option values="56">Kennen</option>
        <option values="57">Kha'Zix</option>
        <option values="58">Kindred</option>
        <option values="59">Kled</option>
        <option values="60">Kog'Maw</option>
        <option values="61">LeBlanc</option>
        <option values="62">Lee Sin</option>
        <option values="63">Leona</option>
        <option values="64">Lissandra</option>
        <option values="65">Lucian</option>
        <option values="66">Lulu</option>
        <option values="67">Lux</option>
        <option values="68">Malphite</option>
        <option values="69">Malzahar</option>
        <option values="70">Maokai</option>
        <option values="71">Master Yi</option>
        <option values="72">Miss Fortune</option>
        <option values="73">Mordekaiser</option>
        <option values="74">Morgana</option>
        <option values="75">Nami</option>
        <option values="76">Nasus</option>
        <option values="77">Nautilus</option>
        <option values="78">Nidalee</option>
        <option values="79">Nocturne</option>
        <option values="80">Nunu e Willump</option>
        <option values="81">Olaf</option>
        <option values="82">Orianna</option>
        <option values="83">Ornn</option>
        <option values="84">Pantheon</option>
        <option values="85">Poppy</option>
        <option values="86">Pyke</option>
        <option values="87">Quinn</option>
        <option values="88">Rakan</option>
        <option values="89">Rammus</option>
        <option values="90">Rek'sai</option>
        <option values="91">Renekton</option>
        <option values="92">Rengar</option>
        <option values="93">Riven</option>
        <option values="94">Rumble</option>
        <option values="95">Ryze</option>
        <option values="96">Sejuani</option>
        <option values="97">Shaco</option>
        <option values="98">Shen</option>
        <option values="99">Shyvana</option>
        <option values="100">Singed</option>
        <option values="101">Sion</option>
        <option values="102">Sivir</option>
        <option values="103">Skarner</option>
        <option values="104">Sona</option>
        <option values="105">Soraka</option>
        <option values="106">Swain</option>
        <option values="107">Syndra</option>
        <option values="108">Tahm Kench</option>
        <option values="109">Taliyah</option>
        <option values="110">Talon</option>
        <option values="111">Taric</option>
        <option values="112">Teemo</option>
        <option values="113">Thresh</option>
        <option values="114">Tristana</option>
        <option values="115">Trundle</option>
        <option values="116">Tryndamere</option>
        <option values="117">Twisted Fate</option>
        <option values="118">Twitch</option>
        <option values="119">Udyr</option>
        <option values="120">Urgot</option>
        <option values="121">Varus</option>
        <option values="122">Vayne</option>
        <option values="123">Veigar</option>
        <option values="124">Vel'Koz</option>
        <option values="125">Vi</option>
        <option values="126">Viktor</option>
        <option values="127">Vladimir</option>
        <option values="128">Volibear</option>
        <option values="129">Warwick</option>
        <option values="130">Wukong</option>
        <option values="131">Xayah</option>
        <option values="132">Xerath</option>
        <option values="133">Xin Zhao</option>
        <option values="134">Yasuo</option>
        <option values="135">Yorick</option>
        <option values="136">Zac</option>
        <option values="137">Zed</option>
        <option values="138">Ziggs</option>
        <option values="139">Zilean</option>
        <option values="140">Zoe</option>
        <option values="141">Zyra</option>
      </select>
      <select name="camp4">
        <option value="null">nenhum</option>
        <option value="1">Aatrox</option>
        <option value="2">Ahri</option>
        <option value="3">Akali</option>
        <option value="4">Alistar</option>
        <option value="5">Amumu</option>
        <option value="6">Anivia</option>
        <option value="7">Annie</option>
        <option value="8">Ashe</option>
        <option values="9">Aurelion</option>
        <option values="10">Azir</option>
        <option values="11">Bardo</option>
        <option values="12">Blitzcrank</option>
        <option values="13">Brand</option>
        <option values="14">Braum</option>
        <option values="15">Caitlyn</option>
        <option values="16">Camille</option>
        <option values="17">Cassiopeia</option>
        <option values="18">Cho'Gath</option>
        <option values="19">Corki</option>
        <option values="20">Darius</option>
        <option values="21">Diana</option>
        <option values="22">Dr. Mundo</option>
        <option values="23">Draven</option>
        <option values="24">Ekko</option>
        <option values="25">Elise</option>
        <option values="26">Evelynn</option>
        <option values="27">Ezreal</option>
        <option values="28">Fiddlesticks</option>
        <option values="29">Fiora</option>
        <option values="30">Fizz</option>
        <option values="31">Galio</option>
        <option values="32">Gangplank</option>
        <option values="33">Garen</option>
        <option values="34">Gnar</option>
        <option values="35">Gragas</option>
        <option values="36">Graves</option>
        <option values="37">Hecarim</option>
        <option values="38">Heimerdinger</option>
        <option values="39">Illaoi</option>
        <option values="40">Irelia</option>
        <option values="41">Ivern</option>
        <option values="42">Janna</option>
        <option values="43">Jarvan IV</option>
        <option values="44">Jax</option>
        <option values="45">Jayce</option>
        <option values="46">Jhin</option>
        <option values="47">Jinx</option>
        <option values="48">Kai'Sa</option>
        <option values="49">Kalista</option>
        <option values="50">Karma</option>
        <option values="51">Karthus</option>
        <option values="52">Kassadin</option>
        <option values="53">Katarina</option>
        <option values="54">Kayle</option>
        <option values="55">Kayn</option>
        <option values="56">Kennen</option>
        <option values="57">Kha'Zix</option>
        <option values="58">Kindred</option>
        <option values="59">Kled</option>
        <option values="60">Kog'Maw</option>
        <option values="61">LeBlanc</option>
        <option values="62">Lee Sin</option>
        <option values="63">Leona</option>
        <option values="64">Lissandra</option>
        <option values="65">Lucian</option>
        <option values="66">Lulu</option>
        <option values="67">Lux</option>
        <option values="68">Malphite</option>
        <option values="69">Malzahar</option>
        <option values="70">Maokai</option>
        <option values="71">Master Yi</option>
        <option values="72">Miss Fortune</option>
        <option values="73">Mordekaiser</option>
        <option values="74">Morgana</option>
        <option values="75">Nami</option>
        <option values="76">Nasus</option>
        <option values="77">Nautilus</option>
        <option values="78">Nidalee</option>
        <option values="79">Nocturne</option>
        <option values="80">Nunu e Willump</option>
        <option values="81">Olaf</option>
        <option values="82">Orianna</option>
        <option values="83">Ornn</option>
        <option values="84">Pantheon</option>
        <option values="85">Poppy</option>
        <option values="86">Pyke</option>
        <option values="87">Quinn</option>
        <option values="88">Rakan</option>
        <option values="89">Rammus</option>
        <option values="90">Rek'sai</option>
        <option values="91">Renekton</option>
        <option values="92">Rengar</option>
        <option values="93">Riven</option>
        <option values="94">Rumble</option>
        <option values="95">Ryze</option>
        <option values="96">Sejuani</option>
        <option values="97">Shaco</option>
        <option values="98">Shen</option>
        <option values="99">Shyvana</option>
        <option values="100">Singed</option>
        <option values="101">Sion</option>
        <option values="102">Sivir</option>
        <option values="103">Skarner</option>
        <option values="104">Sona</option>
        <option values="105">Soraka</option>
        <option values="106">Swain</option>
        <option values="107">Syndra</option>
        <option values="108">Tahm Kench</option>
        <option values="109">Taliyah</option>
        <option values="110">Talon</option>
        <option values="111">Taric</option>
        <option values="112">Teemo</option>
        <option values="113">Thresh</option>
        <option values="114">Tristana</option>
        <option values="115">Trundle</option>
        <option values="116">Tryndamere</option>
        <option values="117">Twisted Fate</option>
        <option values="118">Twitch</option>
        <option values="119">Udyr</option>
        <option values="120">Urgot</option>
        <option values="121">Varus</option>
        <option values="122">Vayne</option>
        <option values="123">Veigar</option>
        <option values="124">Vel'Koz</option>
        <option values="125">Vi</option>
        <option values="126">Viktor</option>
        <option values="127">Vladimir</option>
        <option values="128">Volibear</option>
        <option values="129">Warwick</option>
        <option values="130">Wukong</option>
        <option values="131">Xayah</option>
        <option values="132">Xerath</option>
        <option values="133">Xin Zhao</option>
        <option values="134">Yasuo</option>
        <option values="135">Yorick</option>
        <option values="136">Zac</option>
        <option values="137">Zed</option>
        <option values="138">Ziggs</option>
        <option values="139">Zilean</option>
        <option values="140">Zoe</option>
        <option values="141">Zyra</option>
      </select>
      <select name="camp5">
        <option value="null">nenhum</option>
        <option value="1">Aatrox</option>
        <option value="2">Ahri</option>
        <option value="3">Akali</option>
        <option value="4">Alistar</option>
        <option value="5">Amumu</option>
        <option value="6">Anivia</option>
        <option value="7">Annie</option>
        <option value="8">Ashe</option>
        <option values="9">Aurelion</option>
        <option values="10">Azir</option>
        <option values="11">Bardo</option>
        <option values="12">Blitzcrank</option>
        <option values="13">Brand</option>
        <option values="14">Braum</option>
        <option values="15">Caitlyn</option>
        <option values="16">Camille</option>
        <option values="17">Cassiopeia</option>
        <option values="18">Cho'Gath</option>
        <option values="19">Corki</option>
        <option values="20">Darius</option>
        <option values="21">Diana</option>
        <option values="22">Dr. Mundo</option>
        <option values="23">Draven</option>
        <option values="24">Ekko</option>
        <option values="25">Elise</option>
        <option values="26">Evelynn</option>
        <option values="27">Ezreal</option>
        <option values="28">Fiddlesticks</option>
        <option values="29">Fiora</option>
        <option values="30">Fizz</option>
        <option values="31">Galio</option>
        <option values="32">Gangplank</option>
        <option values="33">Garen</option>
        <option values="34">Gnar</option>
        <option values="35">Gragas</option>
        <option values="36">Graves</option>
        <option values="37">Hecarim</option>
        <option values="38">Heimerdinger</option>
        <option values="39">Illaoi</option>
        <option values="40">Irelia</option>
        <option values="41">Ivern</option>
        <option values="42">Janna</option>
        <option values="43">Jarvan IV</option>
        <option values="44">Jax</option>
        <option values="45">Jayce</option>
        <option values="46">Jhin</option>
        <option values="47">Jinx</option>
        <option values="48">Kai'Sa</option>
        <option values="49">Kalista</option>
        <option values="50">Karma</option>
        <option values="51">Karthus</option>
        <option values="52">Kassadin</option>
        <option values="53">Katarina</option>
        <option values="54">Kayle</option>
        <option values="55">Kayn</option>
        <option values="56">Kennen</option>
        <option values="57">Kha'Zix</option>
        <option values="58">Kindred</option>
        <option values="59">Kled</option>
        <option values="60">Kog'Maw</option>
        <option values="61">LeBlanc</option>
        <option values="62">Lee Sin</option>
        <option values="63">Leona</option>
        <option values="64">Lissandra</option>
        <option values="65">Lucian</option>
        <option values="66">Lulu</option>
        <option values="67">Lux</option>
        <option values="68">Malphite</option>
        <option values="69">Malzahar</option>
        <option values="70">Maokai</option>
        <option values="71">Master Yi</option>
        <option values="72">Miss Fortune</option>
        <option values="73">Mordekaiser</option>
        <option values="74">Morgana</option>
        <option values="75">Nami</option>
        <option values="76">Nasus</option>
        <option values="77">Nautilus</option>
        <option values="78">Nidalee</option>
        <option values="79">Nocturne</option>
        <option values="80">Nunu e Willump</option>
        <option values="81">Olaf</option>
        <option values="82">Orianna</option>
        <option values="83">Ornn</option>
        <option values="84">Pantheon</option>
        <option values="85">Poppy</option>
        <option values="86">Pyke</option>
        <option values="87">Quinn</option>
        <option values="88">Rakan</option>
        <option values="89">Rammus</option>
        <option values="90">Rek'sai</option>
        <option values="91">Renekton</option>
        <option values="92">Rengar</option>
        <option values="93">Riven</option>
        <option values="94">Rumble</option>
        <option values="95">Ryze</option>
        <option values="96">Sejuani</option>
        <option values="97">Shaco</option>
        <option values="98">Shen</option>
        <option values="99">Shyvana</option>
        <option values="100">Singed</option>
        <option values="101">Sion</option>
        <option values="102">Sivir</option>
        <option values="103">Skarner</option>
        <option values="104">Sona</option>
        <option values="105">Soraka</option>
        <option values="106">Swain</option>
        <option values="107">Syndra</option>
        <option values="108">Tahm Kench</option>
        <option values="109">Taliyah</option>
        <option values="110">Talon</option>
        <option values="111">Taric</option>
        <option values="112">Teemo</option>
        <option values="113">Thresh</option>
        <option values="114">Tristana</option>
        <option values="115">Trundle</option>
        <option values="116">Tryndamere</option>
        <option values="117">Twisted Fate</option>
        <option values="118">Twitch</option>
        <option values="119">Udyr</option>
        <option values="120">Urgot</option>
        <option values="121">Varus</option>
        <option values="122">Vayne</option>
        <option values="123">Veigar</option>
        <option values="124">Vel'Koz</option>
        <option values="125">Vi</option>
        <option values="126">Viktor</option>
        <option values="127">Vladimir</option>
        <option values="128">Volibear</option>
        <option values="129">Warwick</option>
        <option values="130">Wukong</option>
        <option values="131">Xayah</option>
        <option values="132">Xerath</option>
        <option values="133">Xin Zhao</option>
        <option values="134">Yasuo</option>
        <option values="135">Yorick</option>
        <option values="136">Zac</option>
        <option values="137">Zed</option>
        <option values="138">Ziggs</option>
        <option values="139">Zilean</option>
        <option values="140">Zoe</option>
        <option values="141">Zyra</option>
      </select><br>
      Lane 1
      <select name="lane1">
        <option value="1">topo</option>
        <option value="2">Selva</option>
        <option value="3">Meio</option>
        <option value="4">Atirador</option>
        <option value="5">Suporte</option>
      </select><br>
      Lane 2
      <select name="lane2">
      <option value="1">topo</option>
      <option value="2">Selva</option>
      <option value="3">Meio</option>
      <option value="4">Atirador</option>
      <option value="5">Suporte</option>
    </select><br>
    <input type="submit" name="ENVIAR">
    <?php
include 'connect.php';
    $nick=$_POST['nick'];
    $objetivo=$_POST['objetivo'];
    $estado=$_POST['estado'];
    $camp1=$_POST['camp1'];
    $camp2=$_POST['camp2'];
    $camp3=$_POST['camp3'];
    $camp4=$_POST['camp4'];
    $camp5=$_POST['camp5'];
    $elo=$_POST['elo'];
    $lane1=$_POST['lane1'];
    $lane2=$_POST['lane2'];
    $usuario=$_SESSION["cdusuario"];
    $_SESSION['lolname']=$nick;

    $url = file_get_contents("https://br1.api.riotgames.com/lol/summoner/v3/summoners/by-name/".$_SESSION['lolname']."?api_key=RGAPI-674aac08-7ea8-454a-90e8-8af1fc275e15");
    $content = json_decode($url, true);
  	$_SESSION['profilelol_id'] = $content['id'];
    $idlol = $_SESSION['profilelol_id'];

    $sql = "INSERT INTO `tb_perfillol`(`cd_perfillol`, `nick`, `objetivo`, `estado`, `campeao1`, `campeao2`, `campeao3`, `campeao4`, `campeao5`, `id_elolol`, `id_lane1lol`, `id_lane2lol`, `id_usuario`, `id_equipelol`, `idlol`) VALUES ('','$nick','$objetivo','$estado','$camp1','$camp2','$camp3','$camp4','$camp5','teste','$lane1','$lane2','$usuario',null,'$idlol')";
    if ($conn->query($sql) === TRUE) {
        echo "New record created successfully";
    } else {
        echo "Error: " . $sql . "<br>" . $conn->error;
    }
    ?>
    </form>
  </body>
</html>
